# Generated by Django 4.1.3 on 2023-03-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('id_user', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=50)),
                ('profile_img', models.ImageField(default='blank-prof', upload_to='profile_images')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
